### ISSUE TITLE
No route to service with nsx-t

### ISSUE THREAD

**Issue by hniedlich** [openshift/openshift-ansible-contrib#1097]
Hello,

I need help with integrating openshift with NSX-T. I'm trying versions:
openshift 3.11
nsx-t 2.4
ansible 2.8.1

I'm doing exacly as it is said in in https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.4/nsxt_24_ncp_openshift.pdf
-create bare metal transport nodes
-create every resource needed by installer
-run playbook deploy_cluster.yml

I'm facing issue with "no route to host" when pods want to access for example kubernetes service on ip 172.30.0.1:443, and installation hangs with deploy error on router, registry etc.

Anyone know how to perform proper install with nsx-t? Can't find similar errors via google.

**Comment by dav1x** [comment]
Howdy @hniedlich let me see if I can get an NSX expert to look.

**Comment by yasensim** [comment]
@hniedlich bare metal is a bit tricky since the management of the BM servers are usually not connected to NSX. You need to make sure that bi-directional routing is possible between the openshift nodes and the pods without nat. This means you need to configure NOSNAT rules on the T0 for the traffic from POD subnet to the nodes management subnet. Also you need routing on the underlay network, so nodes can reach the PODs.
