### ISSUE TITLE
AWS: failed with 'dict object' has no attribute 'tag_openshift_role_master'

### ISSUE THREAD

**Issue by dwojciec** [openshift/openshift-ansible-contrib#143]
TASK [instance-groups : Add masters to requisite groups] ***********************
task path: /root/AWS/openshift-ansible-contrib/reference-architecture/aws-ansible/playbooks/roles/instance-groups/tasks/main.yaml:9
fatal: [localhost]: FAILED! => {
    "failed": true
}

MSG:

'dict object' has no attribute 'tag_openshift_role_master'

**Comment by cooktheryan** [comment]
Can you specify the version of ansible you are using? Also, are you using
openshift rpm based playbooks or git clone from openshift-ansible?

**Comment by gt000** [comment]
same issue as Didier's (working on the same usecase for a customer).

- ansible-2.2.0.0-4.el7.noarch
- openshift playbooks installed via "yum install" as described in the readme file.

**Comment by cooktheryan** [comment]
This may be a trivial request but can you ensure you are using the
inventory script in reference-arch/aws-ansible/inventory. A quick thought
would be that since those hosts are in a private subnet the python script
is trying to look up public instances with that tag.  Also, it might be
worth forcing a refresh-cache with the ec2.py located in the reference arch
directory. By refreshing cache you should be able to see all information
about running instances.



Ryan

**Comment by dwojciec** [comment]
Into the ose-on-aws.py the default command is
command='inventory/aws/hosts/ec2.py --refresh-cache %s' % (devnull)
refresh-cache is already used.

**Comment by cooktheryan** [comment]
Can you manually run the command ec2.py and post a gist or if it should be
private send it to rcook@redhat.com ?

**Comment by gt000** [comment]
Ryan,
we are using us-east-2 region because of the other issue Didier opened:
[https://github.com/openshift/openshift-ansible-contrib/issues/142]

I've noticed us-east-2 is not in the default list in [https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/aws-ansible/inventory/aws/hosts/ec2.ini]

Shouldn't the script read the "region" parameter passed to ose-on-aws.py to look for hosts created only in that region ?

**Comment by cooktheryan** [comment]
Ahh ok I believe we have something to work off of now. I dont believe us-east-2 was public around the time that the ec2.ini and ec2.py were added to the repository so the code was not written in ansible/python to support it.  If you currently have the cycles can you replace the ec2.py with this https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py. We can start there. We may need to pull in the ec2.ini as well but that will require us to modify it just a bit to pull just the private subnet images.

**Comment by cooktheryan** [comment]
I just looked at the ec2.ini and I don't believe us-east-2 is listed to be queried

**Comment by gt000** [comment]
Adding us-east-2 to ec2.ini makes the script go forward correctly. It would be interesting to understand the reason for the other issue, which brought us to substitute us-east-1 to us-east-2. 
The message was "CREATE_FAILED  AWS::EC2::Subnet  PublicSubnet3  Value (us-east-1c) for parameter availabilityZone is invalid. Subnets can currently only be created in the following 
availability zones: us-east-1e, us-east-1a, us-east-1b, us-east-1d." 
It seems the script tries to create a subnet in us-east-1c but it seems it's forbidden.

**Comment by cooktheryan** [comment]
Glad we got passed this point. We shall compare notes tomorrow about the
us-east-1 issue. This morning it passed ci in us-east-1 so it may have been
a later in the day aws outage or something with the account. Sometimes
cloudformations will attempt to use a vpc classic subnet which causes
failure
