### ISSUE TITLE
[RFE] Support for Custom SSL Certificates

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-ansible-contrib#553]
## Provided SSL Certificates

With more and more Red Hat customers adopting the Ref Arch for implementation; the need has arisen to provide SSL Certificates for...

1) SSL Certificates for the WebConsole
2) WildCard SSL certificate for 

### Overview

A customer buys SSL certificates for both

```
https://openshift-master.example.com/console
```

And a wildcard SSL certificate for

```
*.apps.example.com
```
Then the `ose-on-aws.py` script is extended to include...

```
--app-pem-cert
--console-pem-cert
```
So when the customer visits `https://openshift-master.example.com` or `https://myapp.app.example.com` they won't get an SSL self singed warning.

### Alternatives

Keep promoting insecure practices like self signed SSL certs?

In all seriousness we should at least provide Steps to how to add these certificates after installation.

### Security Impact

Verified SSL Certs will provide better security

**Comment by glennswest** [comment]
Recommend we use Let's Encrypt in the automation:
https://www.linkedin.com/pulse/solving-high-cost-certificates-glenn-west

**Comment by menardorama** [comment]
Let's encrypt shouldn't be the default solution.

It should at least cover the default options provided by the openshift ansible playbook.

In my company we have already valid wildcard certificates and we don't want to use lets encrypt

**Comment by ribeaud** [comment]
What about [AWS Certificate Manager](https://aws.amazon.com/certificate-manager)? In my opinion, the easiest way to issue official SSL/TLS certificates. And at no charge for *AWS* services. Worked like a charm for any route deployed with _edge_ termination in `*.apps.my-hosted-zone.com namespace`.  My _infra_ **ELB** looks as following:

![elb](https://user-images.githubusercontent.com/13186156/36421819-3d929376-163a-11e8-98fd-312fcdb17a48.png)

However seems to produce a conflict for routes with _passthrough_ termination like **Docker** registry and **Docker** registry console located in the _default_ project. Actually, why are both applications using their own certificate and not the default, self-signed one, provided for any app deployed in the `*.apps.my-hosted-zone.com` namespace?

Interesting enough would be to understand as well how does the traffic look like in such a scenario? From the **ELB** to the destination pod. Hardly found any information or big picture on that one. Any hint?

Many thanks and cheers,

christian

**Comment by naumannt** [comment]
@ribeaud the OpenShift-Registry doesn't support Edge or Reencrypt: [Passthrough is currently the only type of route supported for exposing the secure registry.](https://docs.openshift.com/container-platform/3.7/install_config/registry/securing_and_exposing_registry.html#exposing-the-registry). 
I'm running into the same problem; can't just use ACM to apply the certs to the ELB's because registry does not work that way. 

In general, what would be the right away to implement custom certificates at the moment? Install the cluster through ose-on-aws.py and then run a playbook to replace the automatically created ones on all nodes, on the router and the registry? If so, which playbook should be used?
