### ISSUE TITLE
[RFE] GCP use provided RHEL/CentOS images from Google

### ISSUE THREAD

**Issue by mperezco** [openshift/openshift-ansible-contrib#618]
**Introduction**

The current deployment uploads a RHEL/CentOs image to GCP when the provider has them available.

## **Problem Description**
Uploading a +500MB image through the network, depending on the situation, can be from time and bandwidth consuming to simply impossible. Under certain circumstances uploading a customized image can be beneficial, however, being able to use the provided images makes the whole solution faster to deploy, easier to manage especially under low bandwidth situations, and more convenient.

**Proposed Change**
Add a var to upload images or use provided ones.
For current status:

    rhel_image_type: 'local'
    rhel_image_path: '~/Software/rhel-guest-image-7.3-36.x86_64.qcow2'

For using provided images
    rhel_image_type: 'remote'
    rhel_image_name: 'rhel-7'

*Security Impact*
A review on the provided image could be performed, ensuring that it is ready to receive the installation.
For example, and OpenSCAP check could be performed.

*Other End User Impact*
Faster and more available deployments of OpenShift on GCP

*Performance Impact*
Faster time to deploy

*Other Deployer Impact*
Less bandwidth usage

*Developer Impact*
A new environment can be made available in a different cloud faster.

*Documentation Impact*
The section on configuring the RHEL image to be used would need to be updated.

**Acceptance criteria**
A deployment with a provided RHEL image is done and running.

**Testing**
Perform an OpenShift deployment with a local RHEL image and check it is running OK (i.e. oadm diag)
Perform an OpenShift deployment with a provided RHEL image and check it is running OK (i.e. oadm diag)
Perform an OpenShift deployment with a local CentOS image and check it is running OK (i.e. oadm diag)
Perform an OpenShift deployment with a provided CentOS image and check it is running OK (i.e. oadm diag)

**References**
https://cloud.google.com/compute/docs/quickstart-linux

**Comment by pschiffe** [comment]
Hello, for the origin deployments we are using CentOS image provided by Google. Unfortunately, we can't use the RHEL image from GCE directly, because you can't use your own subscription there. They are premium images, so you are paying more and have access to the base RHEL channels, but not to the OpenShift. There is this program from RH [1], where you can use your subscription in the cloud providers, but you have to enrol there and it cannot be automated. Uploading kvm image from the access portal is probably the best option for now. More info about this in the Google doc [2].

[1] https://www.redhat.com/en/technologies/cloud-computing/cloud-access
[2] https://cloud.google.com/compute/docs/images#os-details

**Comment by mperezco** [comment]
You are right. The way subscriptions are managed implies that this is the way to do it. 
Thanks for the comment
