### ISSUE TITLE
General - DNS settings

### ISSUE THREAD

**Issue by stuartbfox** [openshift/openshift-ansible-contrib#82]
Hi again

When I provision a service, lets say jenkins, the url scheme is `http://{service}-{project}.apps.domain.com` so `http://jenkins-me.apps.domain.com`. Is there a setting to change the separator from - to . so I get this `http://jenkins.me.apps.domain.com`?

**Comment by detiber** [comment]
I don't think there is, outside of overriding the route when exposing it (I could be wrong, though).

I would say, that if you are able to find a way to modify the default (potentially via project templates), that you would need to provide custom certificates for all https services, since the wildcard certificate would not be valid for nested subdomain.

**Comment by stuartbfox** [comment]
That makes sense, thanks
