### ISSUE TITLE
Image are not importable - export/import project scripts are broken

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-ansible-contrib#967]
Images are not exportable and importable due how they keep their metadata.

By suggesting that they are in "import/export" project script you creating the misconception that these scripts even works in this configuration.

I would recommend removing `import/export projects` from the repository, as until imagestreams will get this fixed, you cant fully import/export project.

**Comment by e-minguez** [comment]
@mjudeikis do you mind to elaborate the issue a bit more?
Images are not exported/imported in the scripts, just imagestreams and imagestreamtags.
Regarding removing the scripts, the idea is to fix them if they are broken instead removing them :)
Thx!

**Comment by mjudeikis** [comment]
Its broken in Openshift level, not scripts. 

Thing is that ImageStreams are using Images to construct end object. But it stores Images ref in the status field[2].

K8S api docs[1] stated about State field behavior: 
The PUT and POST verbs on objects MUST ignore the "status" values, to avoid accidentally overwriting the status in read-modify-write scenarios. A /status subresource MUST be provided to enable system components to update statuses of resources they manage.
So in the result, you cant import status back, so it's being dropped on api. 

This renders ImageStream object kinda non-importable. If you have this relationship (imageStream <-> image) somewhere in the files we could construct a script to populate back appropriate etcd keys and trick system to think all is good. 

[1] https://gist.github.com/mjudeikis/5db199e76b7b462389afa34982cf8830 
[2] https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status

**Comment by mjudeikis** [comment]
https://trello.com/c/zyLpXm9E/1360-admins-should-be-able-to-export-and-import-imagestreams

**Comment by mjudeikis** [comment]
We already have few customers who tooks this as base for architecture "lets not upgrade, but build new cluster and migrate" and shot themselves to the foot while trying to restore data to 2nd cluster

**Comment by e-minguez** [comment]
The imagestream export removes the status section [here](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/day2ops/scripts/project_export.sh#L117).

The only issue I had was using deploymentconfigs if they include the 'ImageChange' section. In that case the spec is modified when the imagestream is changed instead pointing directly to the imagestream, that's why the dcs are exported "patched" [here](https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/day2ops/scripts/project_export.sh#L65-L87)

A running example using the ruby-ex template:

```
$ oc new-project test001
...
$ oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
...
$ oc get pods
NAME              READY     STATUS      RESTARTS   AGE
ruby-ex-1-build   0/1       Completed   0          3m
ruby-ex-1-p6dbh   1/1       Running     0          3m
$ ~/openshift-ansible-contrib/reference-architecture/day2ops/scripts/project_export.sh test001
...
$ diff test001/dc_*
46c46
<             "image": "docker-registry.default.svc:5000/test001/ruby-ex@sha256:70a9d259e1ee998f2c3e41a1b92c2f84bc90a08c1b46893a158602066e904237",
---
>             "image": "ruby-ex:latest",
```

Then, pointing to another OCP cluster:

```
$ ~/openshift-ansible-contrib/reference-architecture/day2ops/scripts/project_import.sh test001/
...
$ for bc in $(oc get bc -o jsonpath="{.items[*].metadata.name}")
do
    oc start-build ${bc}
done
build "ruby-ex-2" started
$ oc get pods
NAME              READY     STATUS      RESTARTS   AGE
ruby-ex-2-2dl85   1/1       Running     0          34s
ruby-ex-2-build   0/1       Completed   0          1m
```

I think maybe I'm missing something from your concerns but I can't see it :(

**Comment by mjudeikis** [comment]
Try replicating this on your end:
1. execute Build which produces Imagestream and image
```
-bash-4.2# oc get pods
NAME              READY     STATUS             RESTARTS   AGE
ruby-ex-1-build   1/1       Running            0          3m
-bash-4.2# oc get pods
NAME              READY     STATUS      RESTARTS   AGE
ruby-ex-1-bqgz7   1/1       Running     0          45s
ruby-ex-1-build   0/1       Completed   0          4m
-bash-4.2# oc get is
NAME              DOCKER REPO                                             TAGS      UPDATED
ruby-22-centos7   docker-registry.default.svc:5000/demo/ruby-22-centos7   latest    5 hours ago
ruby-ex           docker-registry.default.svc:5000/demo/ruby-ex           latest    About a minute ago
#IS uses ref in status field:
-bash-4.2# oc get is ruby-ex -o yaml 
apiVersion: v1
kind: ImageStream
...
status:
  dockerImageRepository: docker-registry.default.svc:5000/demo/ruby-ex
  tags:
  - items:
    - created: 2018-03-12T17:19:30Z
      dockerImageReference: docker-registry.default.svc:5000/demo/ruby-ex@sha256:8e4b97b8c99200917a6b6a42555a5d353b77aebfc2c8be13a6fc1f8311499d04
      generation: 2
      image: sha256:8e4b97b8c99200917a6b6a42555a5d353b77aebfc2c8be13a6fc1f8311499d04
    tag: latest
```
2. Export imageStream and images and delete old is
```
-bash-4.2# oc export is ruby-ex -o yaml > ruby-ex.yaml 
-bash-4.2# oc delete is ruby-ex
imagestream "ruby-ex" deleted
```
3. Recreate ImageStream 
```
-bash-4.2# oc create -f ruby-ex.yaml 
imagestream "ruby-ex" created
-bash-4.2# oc get is
NAME              DOCKER REPO                                             TAGS      UPDATED
ruby-22-centos7   docker-registry.default.svc:5000/demo/ruby-22-centos7   latest    5 hours ago
ruby-ex           docker-registry.default.svc:5000/demo/ruby-ex           latest    
-bash-4.2# oc get is ruby-ex -o yaml
apiVersion: v1
kind: ImageStream
...
status:
  dockerImageRepository: docker-registry.default.svc:5000/demo/ruby-ex
  tags:
  - conditions:
    - generation: 2
      lastTransitionTime: 2018-03-12T17:22:40Z
      message: dockerimage.image.openshift.io "docker-registry.default.svc:5000/demo/ruby-ex:latest"
        not found
      reason: NotFound
      status: "False"
      type: ImportSuccess
    items: null
    tag: latest
```
And see that now does not see to which images it refers:
```
-bash-4.2# oc get is
NAME              DOCKER REPO                                             TAGS      UPDATED
ruby-22-centos7   docker-registry.default.svc:5000/demo/ruby-22-centos7   latest    5 hours ago
ruby-ex           docker-registry.default.svc:5000/demo/ruby-ex           latest      <<< MISSING IMAGE HERE>>>
-bash-4.2# oc get pods
NAME              READY     STATUS      RESTARTS   AGE
ruby-ex-2-bqgz7   1/1       Running     0          4m
ruby-ex-2-build   0/1       Completed   0          8m
-bash-4.2# oc rollout latest ruby-ex
deploymentconfig "ruby-ex" rolled out
-bash-4.2# oc get pods
NAME               READY     STATUS         RESTARTS   AGE
ruby-ex-2-bqgz7    1/1       Running        0          4m
ruby-ex-2-build    0/1       Completed      0          8m
ruby-ex-3-deploy   1/1       Running        0          6s
ruby-ex-3-xv97n    0/1       ErrImagePull   0          3s

```

So your imageStream is redered usless... you need to rebuild app fully, and sometimes this is not possible.

**Comment by mjudeikis** [comment]
And your example works because you execute build. So you rebuilded the image, and not using iteration 1 image. Now if you have 10 imagesStreams with history, and no BuildConfig, or they are not able to rebuild old releases (no tagging, release branches, etc) there is no way to now get old images tags, as you lost mapping...

**Comment by abaxo** [comment]
+1 - IHAC who was hoping to use this as part of their DR strategy. Imagestream creation works fine, but unfortunately there is no way to tell Openshift what tags/images used to exist in the image stream are mapped to which data in the registry. This means if you try and deploy an image in a namespace which has been restored in this way, the image data still doesn't exist until you rebuild the container - and Openshift image data.

**Comment by mjudeikis** [comment]
Please validate this as this is already incorporated in the docs  https://github.com/openshift/origin/pull/18918 
So if not covered fully it might have big consequences if used without understanding.
cc: @bparees @csrwng

**Comment by e-minguez** [comment]
Do you think will be enough removing the imagestream export/import process from the scripts and adding a warning in the docs and in the scripts themselves specifying the imagestream export/import process doesn't work due to OpenShift limitations?
The scripts can still be handy for the rest of resources though.
Thoughts?

**Comment by mjudeikis** [comment]
It tricky, because all our examples use ImageStreams. Ann oc new-app/process/etc generates imageStream objects. We might run into even bigger data loss while not exporting one type of obejcts.

People could use this only if they use k8s native objects, and with no guarantees too. I personally am against this "export, import" practices overall. While we don't have confirmation that each and every object can be exported like this and this is being tested by QA teams (or automated testing) as valid lifecycle strategy for each component, it is impossible to give any promises that this will work in prod.

My main concern is around when this kind of scripts is getting incorporated to High-level design "on sites" as valid DR strategies, or "lifecycle methods" by people who don't understand underlying concepts. We will get into uncomfortable situations with data loss and unrecoverable data. (I personally had 3 "image stream data losses already", 2 was received, 1 dead loss) just because somebody hooked on this idea.

Especially if it lands to the docs (nobody reads the warning, they just take ideas and patterns from the docs).

I would like to hear wider opinions about this, as we have to be cautious what we put out under `openshift` organization codebase and in the docs.

**Comment by e-minguez** [comment]
In the official docs we have two different approaches regarding project object backup:

* [Admin Guide](https://docs.openshift.com/container-platform/3.7/admin_guide/backup_restore.html#project-backup). This procedure has been there for quite a long time, but it is not complete as there are a lot of objects not exported and it doesn't strip unneeded metadata.

* [Day 2 Ops](https://docs.openshift.com/container-platform/3.7/day_two_guide/project_level_tasks.html#day-two-guide-project-backup). We tried to improve it by adding more namespaced objects (all?) and to make things easy to users, we created those wrapper scripts. There are a couple of warnings there saying this is unsupported and a non official tool (I agree with you that nobody reads the warnings) as we do in our reference architecture papers.

The main reason on why I opened https://github.com/openshift/origin/pull/18918 was because I think it would be nice to clarify if we want to provide users a tool to be able to export/import their project objects as there are plenty of valid use cases for the tool to exist (DR, fatfingers user deleting some object, migrate from one cluster to another, etc.) or if we have some tool in the roadmap.

As you said, it would be nice to hear wider opinions on this as well (and if that's the case, I certainly will create a PR for the docs to remove any reference on the scripts)

**Comment by bparees** [comment]
we also have some discussion around app promotion which you can consider a form of backup/restore:
https://docs.openshift.org/latest/dev_guide/application_lifecycle/promoting_applications.html

And it does a decent job of at least preparing you for all the things you need to think about when moving application config+images.

**Comment by e-minguez** [comment]
Just to clarify then, I'm going to try to summarize:

* The current OCP backup/restore scripts created in the o-a-c repo don't cover all OCP objects due to OCP objects limitations (such as ImageStreams) as @mjudeikis explained in this issue (thx!).
* [The admin guide](https://docs.openshift.com/container-platform/3.7/admin_guide/backup_restore.html#project-backup) explains a backup/restore procedure which is not complete as there are a lot of objects not exported and it doesn't strip unneeded metadata.
* [Day 2 ops guide](https://docs.openshift.com/container-platform/3.7/day_two_guide/project_level_tasks.html#day-two-guide-project-backup) explains a backup/restore procedure that should be covering all objects but due to some object limitations, the restore mechanism doesn't work for them (imagestreams)
* There is a [RFE](https://bugzilla.redhat.com/show_bug.cgi?id=1303205) asking for this in "NEW" status for quite a long time.
* There is an app promotion procedure [documented](https://docs.openshift.org/latest/dev_guide/application_lifecycle/promoting_applications.html) that can be seen as a backup/restore procedure.
* Is this backup/restore really needed? Users should be able to deploy their objects by themselves. Objects definition files should be stored in their own vcs, k8s/OCP is just the current status (Infrastructure-as-code). There are plenty of valid use cases for the tool to exist though (DR, fatfingers user deleting some object, migrate from one cluster to another, etc.)
* What is the official Red Hat answer to the "How to create a project backup?" question?

Next steps/Questions:
* Should I deprecate the scripts or just warn users that some objects are not exported properly due to their own nature?
* Who can answer the "How to create a project backup?" question?

I'm adding @cooktheryan to the conversation and @jorgemoralespou as field product manager​ & developer advocate in case they can show us some light on this.

Thank you all.

**Comment by abaxo** [comment]
Thanks @e-minguez , good summary. I have a couple of points to contribute on this:

- Promotion between environments is not a substitute for proper backup/restore
- Enterprise customers want to be able to export everything and put it back again, a build of the app can be problematic depending on the development methodology that is in use
- There is a misunderstanding that you can put the registry data back behind a registry, and be able to use it
- Scripts published in these repos are viewed as a good, functional start and its not necessarily expected that things don't work 

I personally found the scripts useful as a starting point, but I think they need to be updated to A) carry a warning about their limitations and B) remove the export/import of images. Image streams are necessary for builds to work, I don't think we stand to gain anything by pulling that out.

**Comment by jorgemoralespou** [comment]
CC/ @sspeiche
